version: '3.4'
services:
  s_uploader-app:
    container_name: uploader-app
    build: .
    ports:
      - 3000:3000
    volumes:
      - uploader-app-uploads:/uploads
volumes:
  uploader-app-uploads: